name: interview_task

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.3.3 # for handling json serialization and creating immutable objects
  built_collection: ^5.1.1
  http: ^0.13.4
  intl: ^0.17.0
  email_validator: ^2.1.17
  fluttertoast: ^8.1.1
  http_interceptor: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
          weight: 400
        - asset: fonts/Poppins-Medium.otf
          weight: 500
        - asset: fonts/Poppins-SemiBold.otf
          weight: 600