name: mvc_flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.9.1 # for handling json serialization and creating immutable objects
  built_collection: ^5.1.1
  cupertino_icons: ^1.0.6
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  email_validator: ^2.1.17
  flutter_screenutil: ^5.9.0
  http_interceptor: ^1.0.2
  http: ^0.13.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/error_png/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
          weight: 400
        - asset: fonts/Poppins-Medium.otf
          weight: 500
        - asset: fonts/Poppins-SemiBold.otf
          weight: 600